name: viresnet
channels:
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - scikit-image=0.16.2
  - scipy=1.4.1
  - tifffile=2020.2.16
  - matplotlib=3.2.0
  - matplotlib-base=3.2.0
  - natsort=7.0.1
  - opencv=4.2.0
  - libopencv=4.2.0
  - py-opencv=4.2.0  

